### ISSUE TITLE
Adding the pandoc-xnos filter

### ISSUE THREAD

**Issue by Mahraz66** [allefeld/atom-pandoc-pdf#5]
Hi, 
Nice pakage.
I am laso using xnos filters, so I just change the code a little:

`
        case 'Latexmk + XeLaTeX':

        args.push('--pdf-engine=latexmk')
       args.push('--pdf-engine-opt=-pdfxe')
        args.push('--pdf-engine-opt=-output-directory=' + this.tempDir)
        args.push('--filter=pandoc-xnos')
        args.push('--citeproc')
        break
`
Maybe you can also add this option to this package

**Comment by allefeld** [comment]
Hi, I don't want to add many options to the package, because every user has their own preferences. I recommend to use the [default file](https://pandoc.org/MANUAL.html#default-files) system instead. You can put a general or a writer-specific default file into the Pandoc directory, or a document-specific one into the current directory.
